### PR TITLE
Upgrade serie 2.5

### PR DESCRIPTION
**Pull request by cchantep**
Make sure it's source compatible with latest 2.5.x version.

For now using contrib 0.9 get binary compat issue:

```
Exception in thread "specs2-3" java.lang.NoSuchMethodError: akka.testkit.TestProbe.awaitAssert(Lscala/Function0;Lscala/concurrent/duration/Duration;Lscala/concurrent/duration/Duration;)V
	at akka.stream.contrib.TestKit$.$anonfun$assertAllStagesStopped$1(TestKit.scala:31)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at akka.testkit.TestKitBase.within(TestKit.scala:360)
	at akka.testkit.TestKitBase.within$(TestKit.scala:348)
	at akka.testkit.TestKit.within(TestKit.scala:896)
	at akka.testkit.TestKitBase.within(TestKit.scala:374)
	at akka.testkit.TestKitBase.within$(TestKit.scala:374)
	at akka.testkit.TestKit.within(TestKit.scala:896)
	at akka.stream.contrib.TestKit$.assertAllStagesStopped(TestKit.scala:29)
	at CursorSpec.$anonfun$new$3(CursorSpec.scala:52)
	at org.specs2.matcher.MatchResult$$anon$12.$anonfun$asResult$1(MatchResult.scala:344)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:119)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:344)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:15)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:119)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:119)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$result$1(Execution.scala:305)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$3(Execution.scala:323)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:119)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:23)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:119)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$2(Execution.scala:323)
	at org.specs2.specification.core.Execution.$anonfun$startExecution$3(Execution.scala:135)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by cchantep** [comment]
Thx. Do you know when it will be published, at least as snapshot?

**Comment by 2m** [comment]
Just published a snapshot to sonatype snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/akka/akka-stream-contrib_2.12/0.9+19-a0bb1e41-SNAPSHOT/

**Comment by cchantep** [comment]
Thx @2m

**Comment by cchantep** [comment]
I get the same issue with the snapshot:

```
> show test:libraryDependencies
...
[info] * com.typesafe.akka:akka-stream:2.5.13
[info] * com.typesafe.akka:akka-slf4j:2.5.13:test
[info] * com.typesafe.akka:akka-stream-testkit:2.5.13:test
[info] * com.typesafe.akka:akka-stream-contrib:0.9+19-a0bb1e41-SNAPSHOT:test
```

```
Exception in thread "specs2-8" java.lang.NoSuchMethodError: akka.testkit.TestProbe.awaitAssert(Lscala/Function0;Lscala/concurrent/duration/Duration;Lscala/concurrent/duration/Duration;)V
	at akka.stream.contrib.TestKit$.$anonfun$assertAllStagesStopped$1(TestKit.scala:33)
```

It would really be nice to have `assertAllStagesStopped` in the testkit.

**Comment by johanandren** [comment]
@cchantep if you haven't seen yet, it is in progress: akka/akka#25234

**Pull request merged**
