### PR TITLE
Upgrade to Akka 2.4.9-RC1

### PR DESCRIPTION
**Pull request by Sebruck**
I also want to upgrade [akka-sse](https://github.com/hseeberger/akka-sse), but therefore this projects needs to be upgraded first because akka-sse depends on it.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @Sebruck,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
RC2 in a few minutes 😉

**Comment by Sebruck** [comment]
So I'll wait for it and add another commit?

**Comment by ktoso** [comment]
I'm not sure we want to upgrade during the RC phase here. 
Will let @drewhk and @johanandren call the shots here

**Comment by johanandren** [comment]
Let's wait until 2.4.9 and upgrade the dep when that is released. You can always try it out locally without this change.

**Comment by 2m** [comment]
Going to close this PR until 2.4.9 is out.

**Pull request closed without merging**
